const mockData = [
  {
    id: 1,
    submitted_date: "2021/10/5 19:01:00",
    name: "홍길동",
    year_of_birth: "1996/12/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "Low",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 2,
    submitted_date: "2021/10/5 19:02:30",
    name: "김길동",
    year_of_birth: "1998/01/23",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 3,
    submitted_date: "2021/10/5 19:12:30",
    name: "이길동",
    year_of_birth: "1987/10/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 4,
    submitted_date: "2021/10/5 19:14:30",
    name: "고길동",
    year_of_birth: "1954/08/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "Low",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 5,
    submitted_date: "2021/10/5 20:02:10",
    name: "조길동",
    year_of_birth: "1977/04/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 6,
    submitted_date: "2021/10/5 20:04:30",
    name: "하길동",
    year_of_birth: "1993/01/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 7,
    submitted_date: "2021/10/5 19:01:00",
    name: "홍길동",
    year_of_birth: "1996/12/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "Low",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 8,
    submitted_date: "2021/10/5 19:02:30",
    name: "김길동",
    year_of_birth: "1998/01/23",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 9,
    submitted_date: "2021/10/5 19:12:30",
    name: "이길동",
    year_of_birth: "1987/10/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 10,
    submitted_date: "2021/10/5 19:14:30",
    name: "고길동",
    year_of_birth: "1954/08/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "Low",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 11,
    submitted_date: "2021/10/5 20:02:10",
    name: "조길동",
    year_of_birth: "1977/04/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 12,
    submitted_date: "2021/10/5 20:04:30",
    name: "하길동",
    year_of_birth: "1993/01/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 13,
    submitted_date: "2021/10/5 20:04:30",
    name: "하길동",
    year_of_birth: "1993/01/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 14,
    submitted_date: "2021/10/5 20:04:30",
    name: "하길동",
    year_of_birth: "1993/01/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
  {
    id: 15,
    submitted_date: "2021/10/5 20:04:30",
    name: "하길동",
    year_of_birth: "1993/01/01",
    test_name: "위더스제약_세악틸정 250밀리그램",
    video_length: "1:30",
    accuracy: "High",
    details: {
      subject_face: "img file",
      subject_detail: {
        registration_number: "R-00456",
        remaining_intake_count: 11,
        pill_verification: "검토필요",
        subject_verification: "정상",
        intake_verification: "정상",
        subject_mouth_verification: "정상",
      },
      video_url: "video url for streaming",
    },
  },
];

export default mockData;
